#!/bin/bash
#
# Example panel for LemonBoy's bar

. panel_colors

BGN_BG="#BDBDBD"
BGN_FG="#1D1D1D"

WS_BG="#000000"

WIN_BG="#BDBDBD"
WIN_FG="#0D0D0D"

VOL_FG="#BDBDBD"
VOL_BG="#000000"

NET_FG="#BDBDBD"
NET_BG="#000000"

BAT_FG="#BDBDBD"
BAT_BG="#000000"

DATE_FG="#BDBDBD"
DATE_BG="#000000"

BG="#001D1D1D"

SEP_RIGHT="%{F#000000}%{T3}◤   %{T-}"
SEP_LEFT="%{F#000000}%{T3}◥%{T-}%{B#000000}%{F#BDBDBD}"

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
        SYS*)
          sys_arr=${line#???}
          IFS=""
          IFS="°" read t vol wlan eth bat date <<< $sys_arr

          # date
          time="$SEP_LEFT %{F#5D5D5D}%{F${DATE_FG}} ${date}"

          # volume
          vol="%{B#00000000}%{F#000000}%{T3}◥%{T-}%{B#000000}%{F#BDBDBD}%{F#5D5D5D}  %{F${VOL_FG}}%{B${VOL_BG}}${vol}%{B#008fb6a1}${SEP_RIGHT} "
          vol="${vol::-1}"

          # network
          if [[ ${wlan} != "down " ]] && [[ ${eth} != "down " ]]; then # both up
              net="$SEP_LEFT%{F#5D5D5D}  %{F$NET_FG}%{B$NET_BG}$wlan  %{F#5D5D5D}%{F$NET_FG} ${eth}%{B#008fb6a1}$SEP_RIGHT"
          
              # battery
              battery="$SEP_LEFT%{F#5D5D5D} %{F$BAT_FG}%{B$BAT_BG} ${bat:4}%{B#008fb6a1}$SEP_RIGHT "
              battery="${battery::-1}"
          elif [[ ${wlan} == "down " ]] && [[ ${eth} == "down " ]]; then # both down
              net=" "
          
              # battery
              battery="$SEP_LEFT%{F#5D5D5D} %{F$BAT_FG}%{B$BAT_BG} ${bat:4}%{B#008fb6a1}$SEP_RIGHT "
              battery="${battery::-1}"
          elif [[ ${eth} == "down " ]] && [[ ${wlan} != "down " ]]; then # wifi only
              net="$SEP_LEFT%{F#5D5D5D}  %{F$NET_FG}%{B$NET_BG}${wlan}%{B#008fb6a1}$SEP_RIGHT "

              # battery
              battery="$SEP_LEFT%{F#5D5D5D} %{F$BAT_FG}%{B$BAT_BG} ${bat:4}%{B#008fb6a1}$SEP_RIGHT "
              battery="${battery::-1}"
          elif [[ ${eth} != "down " ]] && [[ ${wlan} == "down " ]]; then # eth only
              net="$SEP_LEFT%{F#5D5D5D}  %{F$NET_FG}%{B$NET_BG}${eth}%{B#008fb6a1}$SEP_RIGHT"
          
              # battery
              battery="$SEP_LEFT%{F#5D5D5D} %{F$BAT_FG}%{B$BAT_BG} ${bat:4}%{B#008fb6a1}$SEP_RIGHT "
              battery="${battery::-1}"
          fi
          sys_infos="${vol} ${net}${battery} ${time}%{B${BG}}"
          ;;
		T*)
			# xtitle output
			title="${line:1} "
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
						;;
					L*)
						# layout
						wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
						;;
                esac
                shift
            done
            ;;
	esac
	#printf "%s\n" "%{l}${wm_infos} ${title}%{r}${sys_infos}"
    printf "%s\n" "%{l}%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${USER}@${HOSTNAME}  ${wm_infos}  ${title}%{F$COLOR_TITLE_BG}%{B#00000000}%{T3}◤   %{T-} %{r}${vol} ${net}${battery} ${time} %{B${BG}}"
done
