#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
/home/neo/.config/bspwm/panel/title.sh > "$PANEL_FIFO" &
/opt/i3status/i3status --config /home/neo/.i3/panel/i3status.conf > "$PANEL_FIFO" &

. panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -f "Terminesspowerline-8" -f "Ionicons-8" -f "Typeface-8"  -f "Serif-7" &

wait
